### ISSUE TITLE
HookError

### ISSUE THREAD

**Issue by NescauQuente** [ItsMadruga/WaRevamp#1]
Eu sei que já ta sendo lançada a v0.0.2, mas vim reportar o erro de qualquer maneira, talvez não tenha sido descoberto ainda ou sla, vai que.

Toda vez que eu abro aplicativo, aparece a mensagem de erro:

### Erro detectado
As seguintes opções estão com erro:
SeparateGroupsHook

### Mais detalhes

![IMG-20241123-WA0014](https://github.com/user-attachments/assets/255f633e-4db3-47ae-8f8c-ee6e7c7ba00c)

Módulo: v0.0.1

Whatsapp: 2.24.23.78 (Atualização automática pausada (não sei se é nescessário, mas algum dia ele vai reclamar que a versão ta desatualizada e bla bla bla))

**Comment by ItsMadruga** [comment]
muito obrigado, ja foi atualizado na versao enviada no canal do telegram
